name: CI-CD

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  ECR_REPO: prod-web-repo
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.set-image-uri.outputs.image-uri }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up QEMU (for Docker buildx)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push to ECR
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Set IMAGE_URI output
        id: set-image-uri
        run: echo "image-uri=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update ECS task definition and service
        run: |
          CLUSTER=prod-ecs-cluster3
          SERVICE=prod-web-service
          TASK_FAMILY=prod-web-task
          CONTAINER_NAME=prod-web-container
          IMAGE_URI=${{ needs.build-and-push.outputs.image-uri }}

          CURRENT_TASK=$(aws ecs describe-services --cluster $CLUSTER --services $SERVICE --query 'services[0].taskDefinition' --output text)
          TASK_JSON=$(aws ecs describe-task-definition --task-definition $CURRENT_TASK --query 'taskDefinition' --output json)

          NEW_TASK=$(echo "$TASK_JSON" | jq "del(.status,.revision,.taskDefinitionArn,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy) | .containerDefinitions |= map(if .name==\"$CONTAINER_NAME\" then .image=\"$IMAGE_URI\" else . end)")

          echo "$NEW_TASK" > /tmp/new-task.json
          aws ecs register-task-definition --cli-input-json file:///tmp/new-task.json

          NEW_TASK_ARN=$(aws ecs list-task-definitions --family-prefix $TASK_FAMILY --sort DESC --max-items 1 --query 'taskDefinitionArns[0]' --output text)
          aws ecs update-service --cluster $CLUSTER --service $SERVICE --task-definition $NEW_TASK_ARN

          echo "✅ ECS service updated with new image: $IMAGE_URI"
